### PR TITLE
Enable specifying subnet ID in pool creation popup windown

### PR DESCRIPTION
**Pull request by dai2050**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dai2050__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by dai2050** [comment]
I was unable to sigh the contribution license agreement, because I am a full time Microsoft employee

**Comment by alfpark** [comment]
Attempting to re-trigger CLA bot.

**Comment by azurecla** [comment]
Hi __@dai2050__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by alfpark** [comment]
Hi @dai2050, can you please resubmit the PR? The CLA bot didn't pick up your org link after-the-fact.

**Comment by dai2050** [comment]
Done :)

**Pull request closed without merging**
