### PR TITLE
Update Python samples to use azure-batch 1.0.0

### PR DESCRIPTION
**Pull request by alfpark**
- Update azure-storage to 0.33.0
- Remove redundant sample5
- Add info about Batch Shipyard

### CODE REVIEW

**Comment by alfpark** [comment]
@annatisch - please take a look when you get a chance.

**Comment by annatisch** [comment]
@alfpark  LGTM
I've also run through all the samples with 1.0 with no trouble.
Though it's worth noting that now one of the SDK runtime dependencies also uses crypto...

**Comment by mmacy** [comment]
@annatisch I believe the crypto requirement will break the Python tutorial on Ubuntu, correct? Should we add the crypto requirements now or in another PR?

https://github.com/Azure/azure-batch-samples/blob/master/Python/Batch/article_samples/python_tutorial_client.py#L262

**Comment by annatisch** [comment]
@mmacy,
The article sample should be fine as it only installs azure-storage (not azure-batch) on the node, which to my knowledge doesn't install the SDK runtime msrest. As long as we stick to 0.32 it should be okay.

**Comment by mmacy** [comment]
@annatisch OK cool, thanks. Also just noticed it forces 030 there, so we should be safe. I'll verify after merge to be sure.

**Comment by alfpark** [comment]
@annatisch should I go ahead and set storage to 0.33.0 then? If we're installing crypto, then we should just go ahead and put the latest version on as well due to the bug fixes.

**Comment by annatisch** [comment]
If we were to go to 0.33 we would need to make additional changes to the samples.
Pool start-up script would need to be supplemented with something like:
sudo apt-get install build-essential libssl-dev libffi-dev python-dev

**Comment by alfpark** [comment]
@annatisch At least for the main samples (not the article samples), the python batch package isn't needed on the pools. I think the only sample that has a start task is the docker sample and that only installs the docker engine.

**Comment by annatisch** [comment]
@alfpark  then it should be fine.
The article sample explicitly references storage version 0.30, so should be protected from changes we make to the requirements.txt

**Pull request merged**
